name: Build Modified PancakeStore

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build IPA
        run: |
          chmod +x ./ipabuild.sh
          ./ipabuild.sh

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: PancakeStore-Modified
          path: PancakeStore.ipa
